version: "3"

services:
  djangoapp:
    restart: always
    build:
      context: ./
      dockerfile: ./docker/djangoapp/Dockerfile
    image: djangoapp
    env_file: ./.env
    container_name: djangoapp
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: bash -c "
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"

  process_task:
    restart: always
    image: djangoapp
    command: bash -c "
      python manage.py migrate &&
      python manage.py runscript src.clock & python manage.py process_tasks"
    env_file: ./.env
    volumes:
      - .:/app
    depends_on:
      - djangoapp

  db:
    image: postgres
    container_name: db_cont
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - db_vol:/var/lib/postgresql/data

volumes:
  db_vol:
  static:
  media:
